# Change these first
owner: yocheco # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portainer
    url: https://8e1bcf3db52a9aa4.p21.rt3.io/
    
assignees: # Users to assign downtime issues (optional)
  - yocheco
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://krown.one/assets/img/logo.svg
  name: Status Home sistem
  introTitle: "**Status** Home sistem"
  introMessage: This a test
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
